### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by cardpuncher**
Initial French translation, not tested in runtime yet, but sending the PR anyway so Mateusz can already take a look at it :)

### CODE REVIEW

**Comment by boeckmann** [comment]
Thanks @cardpuncher. I will merge it as is. We can improve it later. If @mateuszviste can have a look, that would be great.

**Comment by mateuszviste** [comment]
it looks good overall, but there is 2 or 3 places where the strings are too long. like here:

image

I have rearranged things in the NLS directory so there is no need for any devel tools to rebuild translations, you just need to run "REGEN.BAT" and the magic should happen automatically even on a bare vanilla DOS installation. Then it's only a matter of copying the new FDISK.LNG to %NLSPATH% and setting LANG=whatever. I hope this will make it easier for non-developer translators to test translations live.

**Comment by boeckmann** [comment]
> I have rearranged things in the NLS directory so there is no need for any devel tools to rebuild translations, you just need to run "REGEN.BAT" and the magic should happen automatically even on a bare vanilla DOS installation. Then it's only a matter of copying the new FDISK.LNG to %NLSPATH% and setting LANG=whatever. I hope this will make it easier for non-developer translators to test translations live.

For this purpose I set up a translation package. This contains all tools + howto: https://nextcloud.iww.rwth-aachen.de/index.php/s/w8nmaH8gMB9H3Rj

**Comment by mateuszviste** [comment]
Ah, I missed that. I like the how-to very much! Is this package somehow automatically updated? If not, then I am afraid it will quickly become outdated... While the svn content is guaranteed to be always up to date, and one can simply download the "nls" directory via github to get only the interesting NLS bits. Perhaps it would make sense to merge your nice package with the git nls directory?

**Comment by mateuszviste** [comment]
PS. I find the cursor-positioning business not very friendly... I think it might be better to do it automatically when possible, for example by looking at some place-holder characters or other marker in the string (for example like "here I know that I should place the cursor right after the first '[' character")

The ANSI positioning is esp. annoying when the string contains an absolute [x,y], because the translator has no clue what other things will be displayed on screen at the given time, and why the english string wants to place the cursor at some specific position

**Comment by boeckmann** [comment]
Yes we can merge it. I do not like binaries being included in the Git repository. That was the reason providing it via Nextcloud. But I am open for other opinions. If you think its better placed here than it shall be. Do you have some suggestions to improve the how-to?

**Comment by boeckmann** [comment]
> PS. I find the cursor-positioning business not very friendly... I think it might be better to do it automatically when possible, for example by looking at some place-holder characters or other marker in the string (like "here I know that I should place the cursor right after the first '[' character")

There shouldn't be that much positioning sequences. We can replace the few included by code. The majority should be text attribute sequences.

**Comment by mateuszviste** [comment]
I agree that storing binaries in a vcs is not very elegant, and I do not like it either... But I also do not like outdated static packages, so it's a hard choice. :-) Ultimately I think that being inelegant-but-functional is a less bad option than elegant-but-outdated -- but that's only my opinion.

The how to is really nice and clear. Maybe it would be good to mention the possibility to flag strings as "dirty" so they are showing up in logs and are not forgotten.

Here is one "their" to much:
> This is done by first converting all UTF-8 text files to their their code-page counterparts. 

And this might be misinterpreted:
> You should also take care, that the maximum line length does not exceed the total screen width of 80 characters.

Many strings are placed in columns > 0, so their acceptable length may be much shorter than 80 characters.
And even for strings that start at column 0, a length of 80 characters may lead to issues when the string is printed via puts(), because it might produce an extra empty line.

I would also recommend explaining that strings must not be left empty because they will be substituted then by the original EN string.

**Comment by boeckmann** [comment]
Some valid points. I will respect these remarks before checking it into git.

**Pull request merged**
