### PR TITLE
version 1.3.5, mainly code cleanup in regard to the last merge

### PR DESCRIPTION
**Pull request by boeckmann**
Hi! In my fork a tagged this as version 1.3.5. I sadly do not have the permission to push it by myself, so here is the merge request :-)

Greetings, Bernd

### CODE REVIEW

**Comment by PerditionC** [comment]
Sorry, I didn't realize members didn't have access to do really anything.  It looks like to give access you create teams and grant the rights to repositories to the teams, so I created a Developers team, added everyone to it and added the active projects to it.  This should allow you to merge changes and publish releases; if not please let me know.  Thank you for the updates.

**Comment by andrewbird** [comment]
@PerditionC cool, thanks. Although I do like someone else to review/merge my stuff just in case I did something stupid!

**Comment by PerditionC** [comment]
:-)  I still will be reviewing all the changes and can still do the merging for anything that needs it.  You all have shown to be capable developers.  I am sorry if github sent a bunch of messages to anyone,  didn't realize it would cause it to autosubscribe people to the repositories.

**Comment by boeckmann** [comment]
> Sorry, I didn't realize members didn't have access to do really anything. It looks like to give access you create teams and grant the rights to repositories to the teams, so I created a Developers team, added everyone to it and added the active projects to it. This should allow you to merge changes and publish releases; if not please let me know. Thank you for the updates.

Thanks, now it works :-)

I was able to push my local v1.3.5 tag. Is it ok for you if I create a release for it? This should also be the version that goes into T2304 if nothing really bad is found before the end of the month.

**Comment by PerditionC** [comment]
please do

**Pull request merged**
