### PR TITLE
Italian translation

### PR DESCRIPTION
**Pull request by PhoeniXP80**
Added Italian translation

### CODE REVIEW

**Comment by PhoeniXP80** [comment]
Added Italian translation

**Comment by boeckmann** [comment]
Hi @PhoeniXP80. Happy to see that you did the italian translation for FDISK. I will incorporate it into master. However, the current merge request contains line ending changes for some files. That should be changed back prior to merging. We also do not include the fdisk.lng file in the repository, because that is considered a binary build artifact.

There are two possibilities: You may try to change the two things by yourself and push them to your fork, so that I can merge your changes. I can also do the merge "by hand", basically merging only your it_utf8.txt and modifying the makefiles by myself.

Please let me know what fits you best. Greetings, Bernd

**Comment by PhoeniXP80** [comment]
Hi @boeckmann. That's fine with me, can you go ahead and merge the changes manually thanks.

Best regards, Francis.

**Comment by boeckmann** [comment]
This is now added via commit f1afa99. @PhoeniXP80 thanks again for providing this. We will ship this with FDISK 1.3.10, scheduled for release at the end of october. Please inform me if you want to be listed in the contributors file (and under which name).

**Pull request closed without merging**
