### PR TITLE
Make able to compile under Turbo C++ 3.0

### PR DESCRIPTION
**Pull request by micahcochran**
The Turbo C++ 3.0 .PRJ file.  This was copied from the current source code and slightly modified.

In the .PRJ file I set the directories to "." instead of "C:\FFDISK\SOURCE\FDISK\"

This also adds Kitten.   The Cats library is included in the source code.  There are a few catgets functions in the current FDISK code.   As I see it there are three options (1) Kitten, (2) Cats library, or (3) define out catsget functions (NOCATS).

(Note: the NASM code still has to be Assembled separately and copied to the same folder as the C source code.)

Turbo C++ 3.0 runs into issues with the existing MAKEFILE.

Using the .PRJ file, Turbo C++ 3.0 will compile FDISK.EXE.  This isn't adding any new functionally.

This should not conflict with PR #6.  This deals with different files than that pull request.

### CODE REVIEW

**Comment by andrewbird** [comment]
1/ I see that source/fdisk/main.h apparently changed completely? That suggests that the repo needs some policy on line endings setting up to avoid churn. I'd like to see it set to 'auto' for general file i.e.
~~~
* text eol=auto
*.bat eol=crlf
*.com -text
*.prj -text
~~~

@PerditionC I could do that prior to this commit being applied?

2/ Did you also check the Turbo C++ Makefile worked as I see there is one in addition to the binary .prj files? You mention NASM as separate step, I expect you could add the NASM assembly into that Makefile as a prior step to linking, or is it not performed on DOS?

**Comment by andrewbird** [comment]
> Turbo C++ 3.0 runs into issues with the existing MAKEFILE.

I should pay more attention!

**Comment by micahcochran** [comment]
The only change I made to MAIN.H was to #include "kitten.h" and commented out #include "catgets.h".  Yeah, I probably converted it to Unix line endings.

I should pay more attention, too, but the a `.gitattributes` configuration could avoid churn.

> You mention NASM as separate step, I expect you could add the NASM assembly into that Makefile as a prior step to linking, or is it not performed on DOS?

That would be ideal.  There is a utility in Turbo C++ to convert PRJ files into a Makefile.  That would be a good next step.

**Comment by andrewbird** [comment]
Sure you can see that small diff in the PR description I submitted in #9 . In the future the line endings should just be correct when you check out.

**Comment by micahcochran** [comment]
I cleaned up the MAIN.H, so it shows up as only two lines have changed.

**Review by PerditionC — APPROVED** [review]

**Comment by micahcochran** [comment]
Thank you!

**Pull request merged**
