### PR TITLE
Improve Turkish translations

### PR DESCRIPTION
**Pull request by bitigchi**
This version uses a terminology more in-line with the current FREECOM and other FDOS components.

### CODE REVIEW

**Comment by bitigchi** [comment]
@cardpuncher, I'm not sure why it does not show a line-by-line diff, but please have a look and comment! :)

**Comment by boeckmann** [comment]
> @cardpuncher, I'm not sure why it does not show a line-by-line diff, but please have a look and comment! :)

Seems that the diff algorithm of Github freaked out on this. There are many changed lines, significantly more than lines not changed. Probably because of that.

At the moment I can not merge this request because of the conflict. But when you agreed on which version I should include I will merge it manually.

**Comment by boeckmann** [comment]
I had to add one more string, because I included a check for non-supported operating system (Windows NT, OS/2).

https://github.com/FDOS/fdisk/blob/a9d6fd82b5aaaead3065349b6edef88e9f455996/source/fdisk/nls/en_utf8.txt#L408

Can you please add this?

**Comment by bitigchi** [comment]
@boeckmann will do!

**Comment by bitigchi** [comment]
One thing to mention, I've removed all trailing dots, as to clear screen clutter, and constantly trying to guess alignment issues. How does it look? Please tell if it's better to bring them back.

**Comment by boeckmann** [comment]
I think it's fine. Merged it as is! Dots that are there in the english / german translation do not necessarily have to be there in the turkish translation.

@bitigchi: regarding DosBox: That probably fails because no virtual disk is defined. I can make a small howto how to configure it, if you are interested.

**Comment by bitigchi** [comment]
Oh I see. If that's what needs to be done, I think I can figure it out. If I do not succeed, I'll definitely come ask for help. 😅

**Comment by boeckmann** [comment]
Now that we have working Github Workflows, everytime a commit is made, a new ZIP distribution gets built. If you want to test the latest changes, you may download it from here: https://github.com/FDOS/fdisk/actions. Klick on the build, and scroll down to artifact. There you find fdisk.zip, with the binaries and translations etc.

**Comment by boeckmann** [comment]
To test the translation, either copy nls\fdisk.lng to the bin folder, or set NLSPATH to the nls folder of the zip.

**Pull request merged**
