### PR TITLE
Update French & Turkish translations

### PR DESCRIPTION
**Pull request by cardpuncher**
Update string 0.92 following commit f71e44c040daaadd9e69a5ad53802e46b3427053  (clarify meaning of /MONO in usage).

### CODE REVIEW

**Comment by boeckmann** [comment]
Thanks for the updates. Any idea why the files did not land in the nls directory? Oversight or by intention?

**Comment by cardpuncher** [comment]
On 7.10.2024 14:15, Bernd Böckmann wrote:
> Thanks for the updates. Any idea why the files did not land in the nls 
> directory? Oversight or by intention?

Oversight, I don't know how I missed that. Should I make a new PR or 
would it be easier for you to move the files after merging?

**Comment by boeckmann** [comment]
No problem :) I checked out your repo and copied the changed files over to my clone of the official repo. So I will close this merge request and make a new commit with your changed files.

**Comment by boeckmann** [comment]
imported via https://github.com/FDOS/fdisk/commit/db158e6ccec3d1f974bc7dc5d33e36139561266a

**Pull request closed without merging**
